name: act-test-runner-example
description: |
  An example action demonstrating how act-test-runner (https://github.com/pshevche/act-test-runner) can be used to implement end-to-end tests.
  The action itself simply echoes comments posted on an issue or a PR.
author: Pavlo Shevchenko (https://github.com/pshevche)
inputs:
  github-token:
    description: GitHub token for API authentication
    required: true

runs:
  using: node24
  main: dist/index.js
